### PR TITLE
Revisiting the Dell EMC storage deployment guide for OSP 17.1

### PR DESCRIPTION
**Pull request by jproque-dell**
Required for deployment and certification

### CODE REVIEW

**Comment by jacob0522** [comment]
PowerFlex with RHOSP17.1 guide is LGTM

**Comment by jacob0522** [comment]
PowerFlex with RHOSP17.1 guide is LGTM

**Review by jacob0522 — APPROVED** [review]

**Review by YianZong — COMMENTED** [review]
LGTM

**Comment by cuiyeliu** [comment]
LGTM

**Comment by TomZhao11** [comment]
should we remove "EMC" and only use "Dell" for branding?

**Pull request merged**
