### PR TITLE
Fixing operation order and connector directory name

### PR DESCRIPTION
**Pull request by jproque-dell**

### CODE REVIEW

**Comment by arkadykanevsky** [comment]
Looks clean.
Looks like this is the fix for the problem that Sam Wan has reported.
Will we need to flip it back from scaleio to powerflex after https://bugzilla.redhat.com/show_bug.cgi?id=1867222 lands?

**Comment by jproque-dell** [comment]
> Looks clean.
> Looks like this is the fix for the problem that Sam Wan has reported.
> Will we need to flip it back from scaleio to powerflex after https://bugzilla.redhat.com/show_bug.cgi?id=1867222 lands?

My two cents, yes. But It depends upon how deep they'll go when refurbishing the driver name.

**Comment by arkadykanevsky** [comment]
This make me worried. I am OK on having a branch we need now that works for z2.
But we need to have a master branch and cut release from it that will match what RH will release in z3.
Our goal is to have z3 clean and for it to include our repo.
We can, of course, have a patch that handle both z2 and z3 and make decision based on the branch. Before and after z3.
But as of now we had not done that anywhere in the code. and I am afraid it will make things messy when we have more RHOSP releases supported and more powerflex options.

**Comment by jproque-dell** [comment]
Your point is not clear to me. 
What is clear is that if the customer follows the documentation as it is written with inappropriate name and order, he'll fail deploying PowerFlex for sure.

**Comment by arkadykanevsky** [comment]
If we merge that and cut release that RH will take into z3 but the name for z3 will be changed by rebranding BZ then in z3 release we will have failure again because directory names will be different again.
I want to avoid it.
What is the best way to align our releases and branches with RHOSP major and minor releases? Do we also want to align with upstream releases?

**Comment by gaelrehault** [comment]
Agree with @arkadykanevsky , we need branches for z2 v z3 to allign with RHOSP releases and this patch should land in the right branch

**Comment by arkadykanevsky** [comment]
How do we move it forward? Separate branches? or one branch handling multiple releases?

**Comment by gaelrehault** [comment]
i d do a branch per release

**Pull request merged**
